 CREATE TABLE `SEO_PAGES` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MID` int(10) unsigned DEFAULT NULL,
  `CREATED_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `GUID` varchar(36) NOT NULL DEFAULT '',
  `DOMAIN` varchar(65) NOT NULL DEFAULT '',
  `ESCAPED_FRAGMENT` varchar(724) NOT NULL DEFAULT '',
  `UNESCAPED_FRAGMENT` varchar(724) NOT NULL DEFAULT '',
  `SITEMAP_SCORE` tinyint(3) unsigned NOT NULL DEFAULT '100',
  `BODY` mediumtext,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `MID` (`MID`,`DOMAIN`,`GUID`,`ESCAPED_FRAGMENT`),
  KEY `ESCAPED_FRAGMENT` (`ESCAPED_FRAGMENT`),
  KEY `DOMAIN` (`DOMAIN`,`UNESCAPED_FRAGMENT`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

