package ZTOOLKIT::AREACODE;


use DBI;
use strict;


## 
## create the persistent handle
##
$SALES::AC_LOOKUP = [
{ state=>'AL',	ac=>205,	ps=>'rickb', tz=>'CST', },
{ state=>'AL',	ac=>251,	ps=>'rickb', tz=>'CST', },
{ state=>'AL',	ac=>256,	ps=>'rickb', tz=>'CST', },
{ state=>'AL',	ac=>334,	ps=>'rickb', tz=>'CST', },
{ state=>'AK',	ac=>907,	ps=>'Frank', tz=>'AKST', },
{ state=>'AZ',	ac=>480,	ps=>'Misti', tz=>'PST', },
{ state=>'AZ',	ac=>520,	ps=>'Misti', tz=>'PST', },
{ state=>'AZ',	ac=>602,	ps=>'Misti', tz=>'PST', },
{ state=>'AZ',	ac=>623,	ps=>'Misti', tz=>'PST', },
{ state=>'AZ',	ac=>928,	ps=>'Misti', tz=>'PST', },
{ state=>'AR',	ac=>479,	ps=>'rickb', tz=>'CST', },
{ state=>'AR',	ac=>501,	ps=>'rickb', tz=>'CST', },
{ state=>'AR',	ac=>870,	ps=>'rickb', tz=>'CST', },
{ state=>'CA',	ac=>209,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>213,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>310,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>323,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>408,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>415,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>424,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>510,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>530,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>559,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>562,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>619,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>626,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>650,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>657,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>661,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>707,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>714,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>760,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>805,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>818,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>831,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>858,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>909,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>916,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>925,	ps=>'Frank', tz=>'PST', },
{ state=>'CA',	ac=>949,	ps=>'Misti', tz=>'PST', },
{ state=>'CA',	ac=>951,	ps=>'Misti', tz=>'PST', },
{ state=>'CO',	ac=>303,	ps=>'Frank', tz=>'MST', },
{ state=>'CO',	ac=>719,	ps=>'Frank', tz=>'MST', },
{ state=>'CO',	ac=>720,	ps=>'Frank', tz=>'MST', },
{ state=>'CO',	ac=>970,	ps=>'Frank', tz=>'MST', },
{ state=>'CT',	ac=>203,	ps=>'Mitch', tz=>'EST', },
{ state=>'CT',	ac=>475,	ps=>'Mitch', tz=>'EST', },
{ state=>'CT',	ac=>860,	ps=>'Mitch', tz=>'EST', },
{ state=>'CT',	ac=>959,	ps=>'Mitch', tz=>'EST', },
{ state=>'DE',	ac=>302,	ps=>'Mitch', tz=>'EST', },
{ state=>'FL',	ac=>239,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>305,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>321,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>352,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>386,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>407,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>561,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>727,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>754,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>772,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>786,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>813,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>850,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>863,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>904,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>941,	ps=>'rickb', tz=>'EST', },
{ state=>'FL',	ac=>954,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>229,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>404,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>470,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>478,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>678,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>706,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>770,	ps=>'rickb', tz=>'EST', },
{ state=>'GA',	ac=>912,	ps=>'rickb', tz=>'EST', },
{ state=>'HI',	ac=>808,	ps=>'Misti', tz=>'HST', },
{ state=>'ID',	ac=>208,	ps=>'Frank', tz=>'MST', },
{ state=>'IL',	ac=>217,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>224,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>309,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>312,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>331,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>464,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>618,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>630,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>708,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>773,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>815,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>847,	ps=>'rickb', tz=>'CST', },
{ state=>'IL',	ac=>872,	ps=>'rickb', tz=>'CST', },
{ state=>'IN',	ac=>219,	ps=>'rickb', tz=>'EST', },
{ state=>'IN',	ac=>260,	ps=>'rickb', tz=>'EST', },
{ state=>'IN',	ac=>317,	ps=>'rickb', tz=>'EST', },
{ state=>'IN',	ac=>574,	ps=>'rickb', tz=>'EST', },
{ state=>'IN',	ac=>765,	ps=>'rickb', tz=>'EST', },
{ state=>'IN',	ac=>812,	ps=>'rickb', tz=>'EST', },
{ state=>'IA',	ac=>319,	ps=>'rickb', tz=>'CST', },
{ state=>'IA',	ac=>515,	ps=>'rickb', tz=>'CST', },
{ state=>'IA',	ac=>563,	ps=>'rickb', tz=>'CST', },
{ state=>'IA',	ac=>641,	ps=>'rickb', tz=>'CST', },
{ state=>'IA',	ac=>712,	ps=>'rickb', tz=>'CST', },
{ state=>'KS',	ac=>316,	ps=>'Frank', tz=>'CST', },
{ state=>'KS',	ac=>620,	ps=>'Frank', tz=>'CST', },
{ state=>'KS',	ac=>785,	ps=>'Frank', tz=>'CST', },
{ state=>'KS',	ac=>913,	ps=>'Frank', tz=>'CST', },
{ state=>'KY',	ac=>270,	ps=>'rickb', tz=>'CST', },
{ state=>'KY',	ac=>502,	ps=>'rickb', tz=>'CST', },
{ state=>'KY',	ac=>606,	ps=>'rickb', tz=>'CST', },
{ state=>'KY',	ac=>859,	ps=>'rickb', tz=>'CST', },
{ state=>'LA',	ac=>225,	ps=>'rickb', tz=>'CST', },
{ state=>'LA',	ac=>318,	ps=>'rickb', tz=>'CST', },
{ state=>'LA',	ac=>337,	ps=>'rickb', tz=>'CST', },
{ state=>'LA',	ac=>504,	ps=>'rickb', tz=>'CST', },
{ state=>'LA',	ac=>985,	ps=>'rickb', tz=>'CST', },
{ state=>'ME',	ac=>207,	ps=>'Mitch', tz=>'EST', },
{ state=>'MD',	ac=>227,	ps=>'Mitch', tz=>'EST', },
{ state=>'MD',	ac=>240,	ps=>'Mitch', tz=>'EST', },
{ state=>'MD',	ac=>301,	ps=>'Mitch', tz=>'EST', },
{ state=>'MD',	ac=>410,	ps=>'Mitch', tz=>'EST', },
{ state=>'MD',	ac=>443,	ps=>'Mitch', tz=>'EST', },
{ state=>'MD',	ac=>667,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>339,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>351,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>413,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>508,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>617,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>774,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>781,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>857,	ps=>'Mitch', tz=>'EST', },
{ state=>'MA',	ac=>978,	ps=>'Mitch', tz=>'EST', },
{ state=>'MI',	ac=>231,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>248,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>269,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>313,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>517,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>586,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>616,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>734,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>810,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>906,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>947,	ps=>'rickb', tz=>'EST', },
{ state=>'MI',	ac=>989,	ps=>'rickb', tz=>'EST', },
{ state=>'MN',	ac=>218,	ps=>'rickb', tz=>'CST', },
{ state=>'MN',	ac=>320,	ps=>'rickb', tz=>'CST', },
{ state=>'MN',	ac=>507,	ps=>'rickb', tz=>'CST', },
{ state=>'MN',	ac=>612,	ps=>'rickb', tz=>'CST', },
{ state=>'MN',	ac=>651,	ps=>'rickb', tz=>'CST', },
{ state=>'MN',	ac=>763,	ps=>'rickb', tz=>'CST', },
{ state=>'MN',	ac=>952,	ps=>'rickb', tz=>'CST', },
{ state=>'MS',	ac=>228,	ps=>'rickb', tz=>'CST', },
{ state=>'MS',	ac=>601,	ps=>'rickb', tz=>'CST', },
{ state=>'MS',	ac=>662,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>314,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>417,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>557,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>573,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>636,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>660,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>816,	ps=>'rickb', tz=>'CST', },
{ state=>'MO',	ac=>975,	ps=>'rickb', tz=>'CST', },
{ state=>'MT',	ac=>406,	ps=>'Frank', tz=>'MST', },
{ state=>'NE',	ac=>308,	ps=>'Frank', tz=>'CST', },
{ state=>'NE',	ac=>402,	ps=>'Frank', tz=>'CST', },
{ state=>'NV',	ac=>702,	ps=>'Frank', tz=>'PST', },
{ state=>'NV',	ac=>775,	ps=>'Frank', tz=>'PST', },
{ state=>'NH',	ac=>603,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>201,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>551,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>609,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>732,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>848,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>856,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>862,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>908,	ps=>'Mitch', tz=>'EST', },
{ state=>'NJ',	ac=>973,	ps=>'Mitch', tz=>'EST', },
{ state=>'NM',	ac=>505,	ps=>'Misti', tz=>'MST', },
{ state=>'NY',	ac=>212,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>315,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>347,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>516,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>518,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>585,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>607,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>631,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>646,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>716,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>718,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>845,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>914,	ps=>'Mitch', tz=>'EST', },
{ state=>'NY',	ac=>917,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>252,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>336,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>704,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>828,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>910,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>919,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>980,	ps=>'Mitch', tz=>'EST', },
{ state=>'NC',	ac=>984,	ps=>'Mitch', tz=>'EST', },
{ state=>'ND',	ac=>701,	ps=>'Frank', tz=>'EST', },
{ state=>'OH',	ac=>216,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>234,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>283,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>330,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>419,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>440,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>513,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>567,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>614,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>740,	ps=>'rickb', tz=>'EST', },
{ state=>'OH',	ac=>937,	ps=>'rickb', tz=>'EST', },
{ state=>'OK',	ac=>405,	ps=>'Misti', tz=>'MST', },
{ state=>'OK',	ac=>580,	ps=>'Misti', tz=>'MST', },
{ state=>'OK',	ac=>918,	ps=>'Misti', tz=>'MST', },
{ state=>'OR',	ac=>503,	ps=>'Frank', tz=>'PST', },
{ state=>'OR',	ac=>541,	ps=>'Frank', tz=>'PST', },
{ state=>'OR',	ac=>971,	ps=>'Frank', tz=>'PST', },
{ state=>'PA',	ac=>215,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>267,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>412,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>445,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>484,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>570,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>610,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>717,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>724,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>814,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>835,	ps=>'Mitch', tz=>'EST', },
{ state=>'PA',	ac=>878,	ps=>'Mitch', tz=>'EST', },
{ state=>'RI',	ac=>401,	ps=>'Mitch', tz=>'EST', },
{ state=>'SC',	ac=>803,	ps=>'Mitch', tz=>'EST', },
{ state=>'SC',	ac=>843,	ps=>'Mitch', tz=>'EST', },
{ state=>'SC',	ac=>864,	ps=>'Mitch', tz=>'EST', },
{ state=>'SD',	ac=>605,	ps=>'Frank', tz=>'CST', },
{ state=>'TN',	ac=>423,	ps=>'rickb', tz=>'CST', },
{ state=>'TN',	ac=>615,	ps=>'rickb', tz=>'CST', },
{ state=>'TN',	ac=>731,	ps=>'rickb', tz=>'CST', },
{ state=>'TN',	ac=>865,	ps=>'rickb', tz=>'CST', },
{ state=>'TN',	ac=>901,	ps=>'rickb', tz=>'CST', },
{ state=>'TN',	ac=>931,	ps=>'rickb', tz=>'CST', },
{ state=>'TX',	ac=>210,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>214,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>254,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>281,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>361,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>409,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>469,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>512,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>682,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>713,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>737,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>806,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>817,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>830,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>832,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>903,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>915,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>936,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>940,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>956,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>972,	ps=>'Misti', tz=>'CST', },
{ state=>'TX',	ac=>979,	ps=>'Misti', tz=>'CST', },
{ state=>'UT',	ac=>435,	ps=>'Frank', tz=>'MST', },
{ state=>'UT',	ac=>801,	ps=>'Frank', tz=>'MST', },
{ state=>'VT',	ac=>802,	ps=>'Mitch', tz=>'EST', },
{ state=>'VA',	ac=>276,	ps=>'Mitch', tz=>'EST', },
{ state=>'VA',	ac=>434,	ps=>'Mitch', tz=>'EST', },
{ state=>'VA',	ac=>540,	ps=>'Mitch', tz=>'EST', },
{ state=>'VA',	ac=>571,	ps=>'Mitch', tz=>'EST', },
{ state=>'VA',	ac=>703,	ps=>'Mitch', tz=>'EST', },
{ state=>'VA',	ac=>757,	ps=>'Mitch', tz=>'EST', },
{ state=>'VA',	ac=>804,	ps=>'Mitch', tz=>'EST', },
{ state=>'WA',	ac=>206,	ps=>'Frank', tz=>'PST', },
{ state=>'WA',	ac=>253,	ps=>'Frank', tz=>'PST', },
{ state=>'WA',	ac=>360,	ps=>'Frank', tz=>'PST', },
{ state=>'WA',	ac=>425,	ps=>'Frank', tz=>'PST', },
{ state=>'WA',	ac=>509,	ps=>'Frank', tz=>'PST', },
{ state=>'WA',	ac=>564,	ps=>'Frank', tz=>'PST', },
{ state=>'DC', ac=>202,	ps=>'Mitch', tz=>'EST', },
{ state=>'WV',	ac=>304,	ps=>'Mitch', tz=>'EST', },
{ state=>'WI',	ac=>262,	ps=>'rickb', tz=>'CST', },
{ state=>'WI',	ac=>414,	ps=>'rickb', tz=>'CST', },
{ state=>'WI',	ac=>608,	ps=>'rickb', tz=>'CST', },
{ state=>'WI',	ac=>715,	ps=>'rickb', tz=>'CST', },
{ state=>'WI',	ac=>920,	ps=>'rickb', tz=>'CST', },
{ state=>'WY',	ac=>307,	ps=>'Frank', tz=>'MST', },
];

##
##
##
sub lookup_areacode {
	my ($AC) = @_;
	my $result = undef;
	foreach my $set (@{$SALES::AC_LOOKUP}) {
		next if ($set->{'ac'} ne $AC);
		$result = $set;
		}
	return($result);
	}

##
##
##
sub areacode_to_state {
	my ($AC) = @_;

	my ($ref) = &lookup_areacode($AC);
	if (not defined $ref) { return("??"); }
	return($ref->{'state'});	
	}



1;