#!/bin/bash

/httpd/scripts/cron/diskspace.pl

for USER in `/httpd/platform/cfgecho.pl type:user` ; do
	echo $USER
	/usr/local/mysql/bin/mysql $USER < /httpd/scripts/cron/optimize-database.sql
done

	

